// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfjfiyimhyhwjaqjjlph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmamZpeWltaHlod2phcWpqbHBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODU2NTMsImV4cCI6MjA2NzU2MTY1M30.zbrHdk428ldH6_J0ZCYchuHDA9T3ZW7jjysBZmRsahM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});